### ISSUE TITLE
能不能加个相册根据名字搜索的功能？

### ISSUE THREAD

**Issue by ChitaGideon** [HengyueLi/baiduphoto#11]
相册名可以重复，新建之前先查询下会比较方便。
而搜索也是很常用的功能

**Comment by HengyueLi** [comment]
这东西底层是做不了，需要自己在上面做。本项目的宗旨是专注低层。你可以自己写一个查询的结构，比如:
```
aList = api.get_self_1page(typeName='Album')
for a in aList['items']:
    print(a.getName())
```

**Comment by ChitaGideon** [comment]
网页版是有相册搜索接口的，不知道你的接口是不是通过网页版来来的
```
https://photo.baidu.com/youai/album/v1/search?clienttype=70&bdstoken=????&keyword=???&limit=30&start=0
```

**Comment by HengyueLi** [comment]
恩 注意到这个接口了。但是我从这里搜不出任何东西。 你有测试过吗？ keyword=后面填写一个东西。我怎么搜不出来？

**Comment by ChitaGideon** [comment]
有用吧，网页版本都能用
登陆之后
带上cookies

<img width="769" alt="image" src="https://github.com/HengyueLi/baiduphoto/assets/1167456/28fecf88-20af-4baa-8a56-9bcf0c88f897">

**Comment by ChitaGideon** [comment]
还有一个接口，也可以顺便加上

还有一个新的接口
```
curl 'https://photo.baidu.com/youai/album/v1/setnotice?clienttype=70&bdstoken=????&album_id=????&tid=????&notice=123' \
  -H 'Accept: application/json, text/plain, */*' \
  -H 'Accept-Language: zh-CN,zh;q=0.9' \
  -H 'Connection: keep-alive' \
  -H 'Cookie: ????????????????????%22%7D' \
  -H 'Referer: https://photo.baidu.com/photo/web/album/????？？？？？？？' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Site: same-origin' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36' \
  -H 'X-Requested-With: XMLHttpRequest' \
  -H 'sec-ch-ua: "Not.A/Brand";v="8", "Chromium";v="114", "Google Chrome";v="114"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  --compressed
```

这个是增加相册公告的接口

<img width="353" alt="image" src="https://github.com/HengyueLi/baiduphoto/assets/1167456/87013ff4-4689-4010-8b1e-07f1335ae388">

**Comment by HengyueLi** [comment]
真是奇怪得很，我换了一台机器试了一下还是不能用。   
比如我现在有个相册叫test123，但是我搜索test却什么也搜不到。是我理解的不对吗？
![Screen Shot 2023-06-17 at 1 16 21 PM](https://github.com/HengyueLi/baiduphoto/assets/20831344/17f86b21-6c70-437c-aec4-eb59ad787313)
![Screen Shot 2023-06-17 at 1 16 34 PM](https://github.com/HengyueLi/baiduphoto/assets/20831344/d54ec5b3-47b0-47d8-a275-e4735888af34)

**Comment by HengyueLi** [comment]
哦。我发现了，很早之前创建的相册不能被搜索到。 可能百度改了点东西。
没关系，这个功能可以做。我搞一搞！～

**Comment by HengyueLi** [comment]
已经更新
