### ISSUE TITLE
batch download

### ISSUE THREAD

**Issue by HengyueLi** [HengyueLi/baiduphoto#4]
选择多个图片批量下载可以直接得到一个zip包，这是相当方便的。但是在下载的时候需要生成一个sign的值。生成这个值的必要信息已经拿到了，但是看不懂生成过程。下面是一个例子，不知道有没有人可以尝试猜猜答案。

# Input
```
{
  "sign1": "a2c0154f9bc90880a8fdcafb130fc86344fffac0",
  "sign2": "function s(j,r){var a=[];var p=[];var o=\"\";var v=j.length;for(var q=0;q<256;q++){a[q]=j.substr((q%v),1).charCodeAt(0);p[q]=q}for(var u=q=0;q<256;q++){u=(u+p[q]+a[q])%256;var t=p[q];p[q]=p[u];p[u]=t}for(var i=u=q=0;q<r.length;q++){i=(i+1)%256;u=(u+p[i])%256;var t=p[i];p[i]=p[u];p[u]=t;k=p[((p[i]+p[u])%256)];o+=String.fromCharCode(r.charCodeAt(q)^k)}return o};",
  "sign3": "d76e889b6aafd3087ac3bd56f4d4053a",
  "timestamp": 1651220609
}
```

# Output
```
I1ItEHuIvfBeuJEx2pb4/iLQ62yrf5XdalQoa5g5sRRMBCEL/l7jYg==
```

**Comment by foxxorcat** [comment]
![图片](https://user-images.githubusercontent.com/95907542/167284698-4aed772c-e195-4533-b93b-d11b37c72134.png)
就是把sing3和sing1使用sing2方法计算然后再计算base64

**Comment by HengyueLi** [comment]
这个截图看起来确实很棒。应该就是你解释的那样。
但是我现在数字还是没有对上。我有点怀疑this.base64Encode不是一个标准的函数。你能帮我看看吗？

**Comment by foxxorcat** [comment]
![图片](https://user-images.githubusercontent.com/95907542/167415647-39b27f8a-a2df-4b0b-93f6-cdf4cfafbee7.png)
计算没有问题，就是标准的base64，请检查你的代码

**Comment by HengyueLi** [comment]
哦，调通了。非常感谢详细的讲解。这很有用。
