### ISSUE TITLE
上传的创建时间不正确

### ISSUE THREAD

**Issue by muyangren907** [HengyueLi/baiduphoto#8]
上传的创建时间（shoot_time）不正确，我发现信息包含在media_info中，media_info的加密方式照着js我写出来了，有空讨论下

**Comment by HengyueLi** [comment]
好的，真棒。
我在隔离，出来了再看。

**Comment by HengyueLi** [comment]
PR 已经合并。  
为了我自己方便管理，我将你的代码单独分离出来了。有空可以看看。
另外，`opencv-python`我感觉是一个很重的包，不知道能不能有优化的空间。
我的初衷是尽量少的依赖第三方的包。

**Comment by HengyueLi** [comment]
经过测试发现有以下问题：
- opencv-python 参与的过程如果去掉，百度服务器会自动补全。如此能减轻咱们这个项目的重量。
- filetype不能识别如heic的格式文件，同时考虑上面相同的原因，也一并去掉。
综上，保留了shoottime的处理部分，对代码做了适当调整。如有问题，还请指正。

**Comment by muyangren907** [comment]
不获取分辨率与时长上传后视频的时长正确吗，我测试是不正确的，我不知道哪里使用的不对。

**Comment by HengyueLi** [comment]
我测试的结果为：
上传以后当时是没有相关信息的。这个时候应该是百度还没有反应过来。一个佐证是点击播放的时候也显示无法播放。
过一会儿，等服务器反应过来了，相关的信息就出现了。
你可以看看你之前上传的那些分辨率和时长不对的对象，现在重新看看是不是对了。
